name: discord.py-starter 

on:
  workflow_dispatch:
  # push: #runs when you push a change to the repo
  # schedule:
  #      - cron: "0 */6 * * *" 
# runs on the 0th minute, every 6 hours (0,6,12,18), every day of month, every month, every day of week 
# because github actions jobs are limited to 6 hours

concurrency: # should prevent two instances of the bot from running at once
  group: ${{ github.workflow }}-${{ github.discord.py-starter }} # can change name to your bot
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: | # install whatever else you need here
        python -m pip install --upgrade pip
        pip install discord.py==1.7.3
        pip install discord-py-slash-command==3.0.3
    - name: execute py script
      env: 
          TOKEN: ${{ secrets.TOKEN }} # sets bot token
      run: |
        python main.py
