name: discord.py-starter 

on:
  workflow_dispatch:
  # push: #runs when you push a change to the repo
  # schedule:
  #       - cron: "0 0 * * *" #runs at 00:00 UTC everyday

concurrency: # should prevent two instances of the bot from running at once
  group: ${{ github.workflow }}-${{ github.discord.py-starter }} # can change name to your bot
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: | # install whatever else you need here
        python -m pip install --upgrade pip
        pip install discord.py
        pip install discord-py-slash-command
    - name: execute py script
      env: 
          TOKEN: ${{ secrets.TOKEN }} # sets bot token
      run: |
        python main.py
